### ISSUE TITLE
Move Logic User story 1 unable to make object property a jquery value that grabs HTML element

### ISSUE THREAD

**Issue by majoseph77** [majoseph77/mancala_game_project1#1]
## Im working on user story 1:
- As a creator I want to create an object that will hold the
  numerical values of each pit on the board. So that the addition
  and subtraction of stones can stay accounted for.
## I attempted this:

`var value= {
  "#a":0,
  "#1":4,
  "#2":4,
  "#3":4,
  "#4":4,
  "#5":4,
  "#6":4,
  "#7":4,
  "#8":4,
  "#9":4,
  "#10":4,
  "#11":4,
  "#12":4,
  "#b":0
};`
- Did not get an error but my property was not linked to the html id despite using that id so i tried to set the property in the context of jQuery

`var value={
$(board[0].text(): 0,
$(board[1].text(): 4,
$(board[2].text(): 4,
$(board[3].text(): 4,
$(board[4].text(): 4,
$(board[5].text(): 4,
$(board[6].text(): 4,
$(board[7].text(): 4,
$(board[8].text(): 4,
$(board[9].text(): 4,
$(board[10].text():4,
$(board[11].text():4,
$(board[12].text(): 4,
$(board[13].text(): 0
};`
- the error I recieved was:
- "Uncaught SyntaxError: Unexpected token [
  at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
  at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
  at Object.InjectedScript.evaluate (<anonymous>:694:21)"
  because apperantley you cant use [ ] to reference the index of an array like this.
- then I attempted to remove the jQuery form by doing this:
  `var value={
  board[0].text(): 0,
  board[1].text(): 4,
  board[2].text(): 4,
  board[3].text(): 4,
  board[4].text(): 4,
  board[5].text(): 4,
  board[6].text(): 4,
  board[7].text(): 4,
  board[8].text(): 4,
  board[9].text(): 4,
  board[10].text():4,
  board[11].text():4,
  board[12].text(): 4,
  board[13].text(): 0
  };`
- but got the same error of:
- Uncaught SyntaxError: Unexpected token [
  at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
  at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
  at Object.InjectedScript.evaluate (<anonymous>:694:21)
- when i use 
  `value = $(board).text();`
- it will return the values i want but in a string

`"
            0
          444444444444
            0
          "`
- I want these numbers to be listen in an array so i attempted this:

`$(board).split().text();`
- And recieved this error:
- Uncaught TypeError: $(...).split is not a function
  at <anonymous>:2:10
  at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
  at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
  at Object.InjectedScript.evaluate (<anonymous>:694:21)
- so then i changed my syntax to this:
  `$(board).text().split();`
- and recieved this:
  `["
          0
        444444444444
          0
        "]'
- It gave me the values I wanted and in an array but they still arent individual they are in a string 
- "-_-  " <------ face of frustration

**Comment by ghost** [comment]
Hi Megan!

Nice frustration face.

There is a lot going on here. I'll start at the top and try to move down.
1. Your user story:
   
   > As a creator I want to create an object that will hold the numerical values of each pit 
   > on the board. So that the addition and subtraction of stones can stay accounted for.
   
   ... is not a good one. The user story should be from the point of view of someone using your 
   application, and hold no specific implementation / coding objectives in it. It may entail some 
   coding objectives (actually, it _must_ entail them), but figuring them out comes next.
2. If you want to represent your HTML elements' IDs, then you can do this.
   
   ``` html
   <div id="0">
   <div id="1">
   <div id="2">
   ```
   
   ``` javascript
   var numDivs = 3; // this is all you need! in fact, you may not even need that!
   for (var i = 0; i < numDivs; i++) {
     console.log($("#" + i));
   }
   ```
   
   ... however, there seems to be no purpose to this. Without knowing your feature / goal it's hard 
   to measure what a good model might look like.
3. For the two `Uncaught SyntaxError`s, you are misusing the object literal syntax by trying to
   assign multiple property keys dynamically at the same time. You'd have to write it like:
   
   ``` javascript
   var value = {};
   value[ $(board)[0].text() ] = 0;
   // ... etc
   ```
4. That last part is a complete mystery to me. :)

**Comment by ghost** [comment]
I'm going to close this, and ask you to resubmit with a user story that describes a feature from the point of view of the user.
