### ISSUE TITLE
Psuedo code for computers first move, have no idea how to hardcode, just need some pointers for starting and examples i can take it from there  :)

### ISSUE THREAD

**Issue by majoseph77** [majoseph77/mancala_game_project1#2]
As a creator I want to create an object that will hold the
numerical values of each pit on the board. So that the addition
and subtraction of stones can stay accounted for.

`var value= {
  "#a":0,
  "#1":4,
  "#2":4,
  "#3":4,
  "#4":4,
  "#5":4,
  "#6":4,
  "#7":4,
  "#8":4,
  "#9":4,
  "#10":4,
  "#11":4,
  "#12":4,
  "#b":0
};`

or

var boardValue=[[4,4,4,4,4,4,0],
              [4,4,4,4,4,4,0]];

## Turn Logic
- As a creator I want the game to be able to determine if a pit has a numeric
  value of 0 or some other numeric value so that it can determine whether
  a players turn has ended or will continue.

var empty= 0;

- As a creator I want to be able to add and subtract numerical values
  from pits #1-12 to coincide with how many stones are being placed into
  each pit. Pits #1-12 all start with a value of 4.
  I only want to add numerical values to pit #a and #b to keep the total
  number of stones in pits #a and #b for the purpose of win logic.

value of pits= i
i>0; board.length; i+

(computerPlayer)

"Beginning values of all pits before any moves"
#7=  4
#8=  4
#9=  4
#10= 4
#11= 4
#12= 4
# b=  0
#6=  4
#5=  4
#4=  4
#3=  4
#2=  4
#1=  4
# a=  0

"Computer moves; pit#10, #b belongs to computer"
#7=  4 -> 4
#8=  4 -> 4
#9=  4 -> 4
#10= 4 -> 0
#11= 4 -> 5
#12= 4 -> 5
# b=  0 -> 1
#6=  4 -> 5
#5=  4 -> 5
#4=  4 -> 4
#3=  4 -> 4
#2=  4 -> 4
#1=  4 -> 4
# a=  0 -> 0

"still computers move last stone was dropped in #5
which is on players side but the pit had an original value
of 4 which is more than 0 so computer picks up original value
of 4 and adds 1 from the original stones of #10 totaling 5 stones
to be dropped in 5 more pits"
#7=  4 -> 5
#8=  4 -> 4
#9=  4 -> 4
#10= 0 -> 0
#11= 5 -> 5
#12= 5 -> 5
# b=  1 -> 1
#6=  5 -> 5
#5=  5 -> 0
#4=  4 -> 5
#3=  4 -> 5
#2=  4 -> 5
#1=  4 -> 5
# a=  0 -> 0

"still computers move last stone was dropped in #7
which is on computers side. computer will take 5 stones
and add 1 to the next 5 pits"
#7=  5 -> 0
#8=  4 -> 5
#9=  4 -> 5
#10= 0 -> 1
#11= 5 -> 6
#12= 5 -> 6
# b=  1 -> 2
#6=  5 ->
#5=  0 ->
#4=  5 ->
#3=  5 ->
#2=  5 ->
#1=  5 ->
# a=  0 ->

"computers 2nd turn, begins with #12"
#7=  0 ->
#8=  5 ->
#9=  5 ->
#10= 1 ->
#11= 6 ->
#12= 6 ->
# b=  2 ->
#6=  5 ->
#5=  0 ->
#4=  5 ->
#3=  5 ->
#2=  5 ->
#1=  5 ->
# a=  0 ->

**Comment by ghost** [comment]
Hi Megan!

I'm not going to close this, but am asking you to respond with a user story that describes a feature from the point of view of the user. No code talk in there! Something like:

```
As a player I would like to see a mancala board when I load the page.
```

or 

```
As a player, I would like to see a mancala board, with an initial setup of seeds
(including those "in the hand") when I visit the page.
```

Also, can you link to a description of the rules of mancala? When I checked out the [Wikipedia page](https://en.wikipedia.org/wiki/Mancala), they suggested variants. I am only familiar with the version they call [bao](https://en.wikipedia.org/wiki/Bao_%28mancala_game%29)... Is that the version whose rules you will follow?

From there, I think we can discuss a good way to model the game.

**Once again, please respond with:**
1. an updated user story you'd like help with, and
2. a link to the rule set you wish to follow.

Thanks!
