### ISSUE TITLE
trying to create decrement function getting error unexpected identifier

### ISSUE THREAD

**Issue by majoseph77** [majoseph77/mancala_game_project1#4]
created onclick function for allPits. 
console.log works
once move function is functional will pass this function to the click function for allPits

Move function:
`move = function (allPits, empty, player1Side, player2Side){
var allPits = document.querySelectorAll(".pits");
for(var i=0; i<allPits.length; i++) {
 allPits[i].innerHTML = numstones[i] ;
}
  for (var i= 4; i <= 0; i--){
    if(i > 0 ){ i++ allPits[i]}
};`

Uncaught SyntaxError: Unexpected identifier

attempted to change syntax and use jquery continued to give same error
allPits[i].innerHTML

**Comment by ghost** [comment]
Please resubmit using the correct structure outlined in the [issues protocol](https://github.com/ga-students/WDI_DTLA_4/tree/master/projects/project_issues_protocol).
